### PR TITLE
some translated into chinese

### PR DESCRIPTION
**Pull request by MeizhouWan**
Additional context

### CODE REVIEW

**Comment by trobonox** [comment]
Thanks for showing interest in translating Kanri. 
What kind of chinese is this if I may ask (zh_cn, zh_hk, ...)? Is this the same as in the PR #700? If so, I would prefer to merge that instead since it is a complete translation rather than a partial one.

**Comment by trobonox** [comment]
If you want to share results with the other person, please make sure you have **one** pull request which includes a complete translation. I am not accepting incomplete translations.

**Comment by MeizhouWan** [comment]
I thank him GU XI FENG <nudgev@outlook.com>
image

**Comment by trobonox** [comment]
Thanks for coming to an agreement between each other and thanks for the translation!

**Pull request merged**
